import pandas
import matplotlib.pyplot as plt
def visual_time_base():
    df2 = pandas.read_csv("base_res.csv",index_col='node_num')
    df2['time'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.show()

def visual_time_coo():
    df = pandas.read_csv("res.csv",index_col='node_num')
    df['time'].plot(c='green',label='improved')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.show()

def visual_time_all():
    df = pandas.read_csv("res.csv",index_col='node_num')
    df2 = pandas.read_csv("base_res.csv",index_col='node_num')
    df['time'].plot(c='green',label='improved')
    df2['time'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.show()

def visual_memory_coo():
    df = pandas.read_csv("res.csv",index_col='node_num')
    df['memory'].plot(c='green',label='improved')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.show()

def visual_memory_base():
    df2 = pandas.read_csv("base_res.csv",index_col='node_num')
    df2['memory'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.show()

def visual_memory_all():
    df = pandas.read_csv("res.csv",index_col='node_num')
    df2 = pandas.read_csv("base_res.csv",index_col='node_num')
    df['memory'].plot(c='green',label='improved')
    df2['memory'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.show()

def freq_base(i):
    df2 = pandas.read_csv(f"rank/base/base_rank_{i}.csv")
    a = list(df2['weight'])
    plt.xlabel("weight")
    plt.ylabel("node")
    plt.hist(a,50)
    plt.show()

def freq_coo(i):
    df = pandas.read_csv(f"rank/coo/rank_{i}.csv")
    a = list(df['weight'])
    plt.xlabel("weight")
    plt.ylabel("node")
    plt.hist(a,50)
    plt.show()

def show_all():
    plt.figure()   
    df = pandas.read_csv("res.csv",index_col='node_num')
    df2 = pandas.read_csv("base_res.csv",index_col='node_num')  
    plt.subplot(321)
    df['time'].plot(c='green',label='improved')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.subplot(322)
    df['memory'].plot(c='green',label='improved')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.subplot(323)
    df2['time'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.subplot(324)
    df2['memory'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.subplot(325)
    df['time'].plot(c='green',label='improved')
    df2['time'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("time(s)")
    plt.legend()
    plt.subplot(326)
    df['memory'].plot(c='green',label='improved')
    df2['memory'].plot(c='red',label='base')
    plt.xlabel("node")
    plt.ylabel("memory(KB)")
    plt.legend()
    plt.show()
